name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Download JUnit
      run: |
        mkdir -p lib
        wget https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar -O lib/junit-4.13.2.jar
        
    - name: Compile Java files -source and test
      run: |
        mkdir -p bin
        javac -cp "lib/*" -d bin $(find src tests -name "*.java")

    - name: Run JUnit Tests
      run: |
        java -cp "bin:lib/*" org.junit.runner.JUnitCore CalculatorTest